### ISSUE TITLE
execute passenger:restart fails

### ISSUE THREAD

**Issue by i5okie** [capistrano/rails#119]
I have chruby on the server.. and in the log, capistrano does run chruby correctly.
This is a new issues since running ```bundle update``` a couple weeks ago. i saw another issue here, which seemed to be related to my problem, which was closed, however it did not fix the problem i have. 

I tried renaming the destination deploy directory on the server, and running ```cap production setup``` followed by ```cap production deploy```, -- it sets everything up, installs all the gems properly, compiles all the assets without issue, but at the end here it gives me this error still.

```
...
** Invoke deploy:restart (first_time)
** Execute deploy:restart
** Invoke passenger:restart (first_time)
** Execute passenger:restart
DEBUG [725c38d2] Running /usr/bin/env passenger -v as deploy@myserver
DEBUG [725c38d2] Command: /usr/bin/env passenger -v
DEBUG [725c38d2] 	/usr/bin/env: ruby: Permission denied
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@myserver: passenger exit status: 126
passenger stdout: Nothing written
passenger stderr: /usr/bin/env: ruby: Permission denied
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/runners/sequential.rb:24:in `rescue in run_backend'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/runners/sequential.rb:21:in `run_backend'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/runners/sequential.rb:16:in `execute'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/coordinator.rb:21:in `each'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:55:in `on'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-passenger-0.0.5/lib/capistrano/tasks/passenger.cap:4:in `block (2 levels) in <top (required)>'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in `invoke'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-passenger-0.0.5/lib/capistrano/tasks/deploy_passenger.cap:6:in `block (2 levels) in <top (required)>'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/dsl/task_enhancements.rb:14:in `block in after'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in `invoke'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:65:in `block (2 levels) in <top (required)>'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:64:in `each'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:64:in `block in <top (required)>'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/Users/ivan/.gem/ruby/2.2.1/bin/cap:23:in `load'
/Users/ivan/.gem/ruby/2.2.1/bin/cap:23:in `<main>'
SSHKit::Command::Failed: passenger exit status: 126
passenger stdout: Nothing written
passenger stderr: /usr/bin/env: ruby: Permission denied
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in `exit_status='
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:179:in `block in _execute'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:77:in `capture'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-passenger-0.0.5/lib/capistrano/tasks/passenger.cap:6:in `block (4 levels) in <top (required)>'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/backends/abstract.rb:85:in `with'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-passenger-0.0.5/lib/capistrano/tasks/passenger.cap:5:in `block (3 levels) in <top (required)>'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/runners/sequential.rb:21:in `run_backend'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/runners/sequential.rb:16:in `execute'
/Users/ivan/.gem/ruby/2.2.1/gems/sshkit-1.7.1/lib/sshkit/coordinator.rb:21:in `each'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:55:in `on'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-passenger-0.0.5/lib/capistrano/tasks/passenger.cap:4:in `block (2 levels) in <top (required)>'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in `invoke'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-passenger-0.0.5/lib/capistrano/tasks/deploy_passenger.cap:6:in `block (2 levels) in <top (required)>'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/dsl/task_enhancements.rb:14:in `block in after'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in `invoke'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:65:in `block (2 levels) in <top (required)>'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:64:in `each'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:64:in `block in <top (required)>'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/ivan/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
/Users/ivan/.gem/ruby/2.2.1/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/Users/ivan/.gem/ruby/2.2.1/bin/cap:23:in `load'
/Users/ivan/.gem/ruby/2.2.1/bin/cap:23:in `<main>'
Tasks: TOP => passenger:restart
The deploy has failed with an error: Exception while executing as deploy@myserver: passenger exit status: 126
passenger stdout: Nothing written
passenger stderr: /usr/bin/env: ruby: Permission denied
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

when sshed into myserver as deploy user:
```
deploy@myserver:~/myapp/current$ /usr/bin/env passenger -v
Phusion Passenger version 5.0.4

"Phusion Passenger" is a trademark of Hongli Lai & Ninh Bui.
deploy@myserver:~/myapp/current$ /usr/bin/env ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

after digging around and experimenting i found that outside of that directory:
```
deploy@myserver:~/myapp/current$ cd ~
deploy@myserver:~$ /usr/bin/env ruby -v
/usr/bin/env: ruby: Permission denied
deploy@myserver:~$ /usr/bin/env passenger -v
/usr/bin/env: ruby: Permission denied
deploy@myserver:~$
```
and it makes sense, since chruby isn't run outside of app directory..
but why would capistrano try to run these commands outside of it?

**Comment by i5okie** [comment]
This is still going on, thought slightly different error:
https://gist.github.com/i5okie/5050f6cc58c62fc00085

```
DEBUG [c9915242] Running /usr/bin/env passenger -v as deploy@myserver
DEBUG [c9915242] Command: ( PATH=/usr/bin/passenger /usr/bin/env passenger -v )
DEBUG [c9915242] 	/usr/bin/env: passenger: Not a directory
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@myserver: passenger exit status: 126
passenger stdout: Nothing written
passenger stderr: /usr/bin/env: passenger: Not a directory
 
SSHKit::Command::Failed: passenger exit status: 126
passenger stdout: Nothing written
passenger stderr: /usr/bin/env: passenger: Not a directory
 
Tasks: TOP => passenger:restart
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@myserver: passenger exit status: 126
passenger stdout: Nothing written
passenger stderr: /usr/bin/env: passenger: Not a directory
```


on the server:
```
SSH into the server as Deploy user:
 
 
deploy@myserver:~$ passenger -v
Phusion Passenger version 5.0.4
 
"Phusion Passenger" is a trademark of Hongli Lai & Ninh Bui.
```

**Comment by jspizziri** [comment]
+1

**Comment by jspizziri** [comment]
https://github.com/capistrano/passenger/issues/26

**Comment by xpepermint** [comment]
+1

**Comment by will-in-wi** [comment]
Is this still an issue? Capistrano Passenger support resides in https://github.com/capistrano/passenger now.
