### ISSUE TITLE
asset-folder symlinks self when public-folder is in linked_dirs

### ISSUE THREAD

**Issue by thedanielhanke** [capistrano/rails#151]
in my case, i link the entire public folder via `linked_dirs`. 

this leads to `shared/public/assets -> shared/public/assets` symlink. 

so i want to be able skip asset-folder symlink creation.

**Comment by NekoNova** [comment]
I'm having the same problem.
This is our `deploy.rb` for the linked_dirs:

```
set :assets_roles, [:web, :vm]

set :linked_files, %w{.chamber.pem Procfile .env}
set :linked_dirs, %w{public data tmp log uploads}

set :keep_releases, 10

set :bundle_path, nil
set :bundle_binstubs, nil
set :bundle_flags, '--system'
```

When I run the command `bundle exec cap deploy`, I receive the following error when the assets precompile runs:

```
rake aborted!
Errno::EEXIST: File exists @ dir_s_mkdir - /home/riskmethods/riskmethods/releases/20160212080011/public/assets
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/sprockets-3.5.2/lib/sprockets/asset.rb:163:in `write_to'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:192:in `block (2 levels) in compile'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/safe_task_executor.rb:24:in `call'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/ivar.rb:170:in `safe_execute'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/future.rb:52:in `block in execute'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:333:in `call'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:333:in `run_task'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:322:in `block (3 levels) in create_worker'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:305:in `loop'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:305:in `block (2 levels) in create_worker'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:304:in `catch'
/home/riskmethods/.rvm/gems/ruby-2.2.3@riskmethods/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:304:in `block in create_worker'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in `exit_status='
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:179:in `block in _execute'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/capistrano-rails-1.1.3/lib/capistrano/tasks/assets.rake:59:in `block (6 levels) in <top (required)>'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/sshkit-1.7.1/lib/sshkit/backends/abstract.rb:85:in `with'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/capistrano-rails-1.1.3/lib/capistrano/tasks/assets.rake:58:in `block (5 levels) in <top (required)>'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/sshkit-1.7.1/lib/sshkit/backends/abstract.rb:77:in `within'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/capistrano-rails-1.1.3/lib/capistrano/tasks/assets.rake:57:in `block (4 levels) in <top (required)>'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
DEBUG [20070146]        I, [2016-02-12T09:00:35.165449 #12105]  INFO -- : Writing /home/riskmethods/riskmethods/releases/20160212080011/public/assets/map/pin_indicator_00-61a4848c99335c2bd2937970ff86c56b960b36936839fd4e14d84bcc82779581.png
Tasks: TOP => deploy:assets:precompile
The deploy has failed with an error: Exception while executing as riskmethods@staging.riskmethods.net: rake exit status: 1
rake stdout: Nothing written
rake stderr:
```

The problem seems to be that adding `public` to the `linked_dirs` path causes some weird behaviour in the deploy.

**Comment by mattbrictson** [comment]
I know this is somewhat of a hack, but could you try this workaround?

```ruby
# In deploy.rb
Rake::Task["deploy:set_linked_dirs"].clear_actions
```

This should disable the capistrano-rails code that injects `public/assets` into `linked_dirs`.

**Comment by thedanielhanke** [comment]
yeah feels hacky to use string-based config to override own DSL.
but thanks for the input, i prefer that over sort-of ignored pull requests ;)
thanks.

**Comment by at-phuocdh** [comment]
I have the same problem. Any idea?
Thanks

**Comment by mattbrictson** [comment]
@at-phuocdh Does the [solution I mentioned](https://github.com/capistrano/rails/issues/151#issuecomment-183440772) work for you? The first step to a solution is figuring out what works and what doesn't.

**Comment by at-phuocdh** [comment]
@mattbrictson I tried. But it's not work. So I tried:
`set :linked_dirs, fetch(:linked_dirs, []).push('log', 'tmp/pids', 'tmp/cache', 'tmp/sockets', 'vendor/assets', 'public/system', 'public/uploads')
`
And it worked.
Anyway, thanks :+1:

**Comment by will-in-wi** [comment]
For this particular case, would it make sense to have `public/assets` conditionally added based on `public/` not being in `:linked_dirs` already?

**Comment by jboler** [comment]
I'm also getting this error. I need a way to disable the symlinking of `public/assets`.

**Comment by mattbrictson** [comment]
@jboler If I create a PR with a possible fix, will you be able to test my branch to verify it works?

**Comment by jboler** [comment]
@mattbrictson Yes - thanks.

**Comment by thedanielhanke** [comment]
a bit late, but its never to late to say thanks! so, since i almost died twice due to this issue...

thank you! :+1: ;-)
