### ISSUE TITLE
"rake db:migrate" gives "fe_sendauth: no password supplied" error

### ISSUE THREAD

**Issue by harsh-parihar** [capistrano/rails#80]
I am getting this error while running Capistrano command when it tries to run "rake db:migrate"

```
INFO[c03035dd] Running ~/.rvm/bin/rvm default do bundle exec rake db:migrate on 128.199.211.80
DEBUG[c03035dd] Command: cd /home/deploy/my_app/releases/20140723173643 && ( RAILS_ENV=production ~/.rvm/bin/rvm default do bundle exec rake db:migrate )
DEBUG[c03035dd]   rake aborted!
DEBUG[c03035dd]   PG::ConnectionBad: fe_sendauth: no password supplied
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `initialize'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `new'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `connect'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_handling.rb:87:in `connection'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:910:in `initialize'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:807:in `new'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:807:in `up'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:785:in `migrate'
DEBUG[c03035dd]   /home/deploy/my_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
DEBUG[c03035dd]   Tasks: TOP => db:migrate
DEBUG[c03035dd]   (See full trace by running task with --trace)
```

**Comment by eduavencama** [comment]
My friend, I was have the same problem. My solution was added the credentials for each environment and  enable the host in th value localhost..

like this:
´´´
development:
  <<: *default
  database: RiskDisasterSM_development
  username: user
  password: xxxx

host: localhost

test:
  <<: *default
  database: RiskDisasterSM_test
  username: user
  password: xxxxxx

production:
  <<: *default
  database: RiskDisasterSM_production
  username: user
  password: xxxxxx
´´´
